# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=100000
setopt autocd
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/fred/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Enviroment
export MYVIMRC='~/.config/vim/vimrc'
export VIMINIT='source $MYVIMRC'
