" vimrc

" Change <leader> key to "-"
let mapleader="-"
	
" Wrap long lines, wrap words
set wrap
set linebreak

" Show current position
set ruler

" Syntax highlighting
syntax enable

" Configure backspace so it acts like excpected
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Ignore case when searching
set ignorecase

" Standard encoding utf8
set encoding=utf8

" tabs are tabs
set tabstop=4
set softtabstop=0 noexpandtab
set shiftwidth=4	

" Compile and run C code (filename.c -> filename.out) Always includes ncurses!
autocmd filetype c nnoremap <Leader>c :w <CR>:!clear && gcc % -o %:r.out -lncurses && clear &&	./%:r.out<CR>

" Show absolute number current line, reletive number other lines
set number
set relativenumber

" Disable arrows keys (normal+insert), because all the cool kids do it.
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

" Backups
set backup
set backupdir=~/documents/vim/backup

" Swap files
set dir=~/documents/vim/swap
